dubbo:
  registry:
    address: 127.0.0.1
    protocol: zookeeper
    port: 2181
  application:
    name: dubbo-service-provider
  scan:
    base-packages: com.hps.dubbo.service
  protocol:
    port: 20880
    name: dubbo